### PR TITLE
first attempt to have compatibility with EllipsisNotation.jl, cf. #39

### LINKED ISSUE #39: Error with view using EllipsisNotation (..)
I get the following error on Julia v1.5.3.
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.add("HybridArrays"); Pkg.add("EllipsisNotation"); Pkg.add("StaticArrays")
[...]
  [1baab800] + HybridArrays v0.4.4
  [da5c29d0] + EllipsisNotation v1.0.0
  [90137ffa] + StaticArrays v1.0.1

julia> using EllipsisNotation, HybridArrays, StaticArrays

julia> u = HybridArray{Tuple{2,StaticArrays.Dynamic()}}(rand(2,10));

julia> view(u, 1, ..)
ERROR: MethodError: no method matching all_dynamic_fixed_val(::Type{Tuple{2,StaticArrays.Dynamic()}}, ::Int64, ::EllipsisNotation.Ellipsis)
Closest candidates are:
  all_dynamic_fixed_val(::Type{Size}, ::Union{Colon, Int64, AbstractArray}...) where Size<:Tuple at ~/.julia/packages/HybridArrays/GeLeK/src/HybridArrays.jl:52
  all_dynamic_fixed_val(::Type{Size}) where Size<:Tuple at ~/.julia/packages/HybridArrays/GeLeK/src/HybridArrays.jl:44
  all_dynamic_fixed_val(::Type{Size}, ::StaticArrays.StaticIndexing{var"#s14"} where var"#s14"<:Union{Colon, Int64, AbstractArray}...) where Size<:Tuple at ~/.julia/packages/HybridArrays/GeLeK/src/HybridArrays.jl:48
Stacktrace:
 [1] view(::HybridArray{Tuple{2,StaticArrays.Dynamic()},Float64,2,2,Array{Float64,2}}, ::Int64, ::EllipsisNotation.Ellipsis) at ~/.julia/packages/HybridArrays/GeLeK/src/indexing.jl:304
 [2] top-level scope at REPL[6]:1
```
This seems to be caused by the interaction of HybridArrays and EllipsisNotation. I thought it is better to open the issue here since it seems to be closer to HybridArrays.

### PR DESCRIPTION
**Pull request by ranocha**
There is a method ambiguity
```julia
  MethodError: getindex(::HybridArray{Tuple{2,StaticArrays.Dynamic()},Float64,2,2,Array{Float64,2}}, ::EllipsisNotation.Ellipsis) is ambiguous. Candidates:
    getindex(A::AbstractArray, ::EllipsisNotation.Ellipsis) in EllipsisNotation at EllipsisNotation/XpBpL/src/EllipsisNotation.jl:58
    getindex(sa::HybridArray{S,T,N,M,TData} where TData<:AbstractArray{T,M} where M where N where T, inds...) where S in HybridArrays at HybridArrays/src/indexing.jl:14
  Possible fix, define
    getindex(::HybridArray{S,T,N,M,TData} where TData<:AbstractArray{T,M} where M where N where T, ::EllipsisNotation.Ellipsis) where S
```
since EllipsisNotation.jl defines
```julia
# avoid copying if indexing with .. alone, see
# https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/214
Base.getindex(A::AbstractArray, ::Ellipsis) = A
```
This can be fixed by removing the current definition
```julia
# general fallback allowing, e.g. `..` from EllipsisNotation.jl
Base.@propagate_inbounds function getindex(sa::HybridArray{S}, inds...) where S
    getindex(sa, to_indices(sa, inds)...)
end
```
in HybridArrays/src/indexing.jl:14. If we do that, we don't catch something like `u_hybrid[1, ..]` anymore, meaning that this will result in an `Array` instead of a `HybridArray` (as it is for `u_hybrid[1, :]`). My best guess is that it would be good to look how something like OffsetArrays.jl deals with this situation (since they work with EllipsisNotation and return an `OffsetArray` appropriately).

I think the basic reason for this is that HybridArrays.jl interrupts directly at the level of `getindex(::HybridArray, inds...)` in general, circumventing the mechanisms of `to_indices` etc. from `Base`. I somehow get the impression that this can't be the best approach since we run into this issue. Something like writing a method
```julia
_unsafe_getindex(::IndexLinear{…},::HybridArray{…},::Int64{…},::Base.Slice{…})
```
does not seem to be the right approach either. Since I'm not an expert on HybbridArrays.jl, I don't really know how to proceed further from here. I could try something but I thought it might be better to share my experience so far and let also others have a look. I'm definitely willing to invest some more work into this, but it will probably be best if others have a look, too.

When we get this correct, it will fix #39.

### CODE REVIEW

**Comment by mateuszbaran** [comment]
This is a great topic. I wrote most of `HybridArrays` when I didn't know as much about indexing as I do now, and there is still a lot that I don't know. First thing I'd like to clear here, do you think `EllipsisNotation` works right with `StaticArrays`? `StaticArrays` indexing should be closer to `HybridArrays` than `OffsetArrays.jl`. I just tried that:

```julia
julia> a = @SMatrix randn(3,3)
3×3 SArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
  0.321819   1.30703    0.165836
 -0.433719  -0.403508   2.25181
  0.404721  -0.568728  -0.282213

julia> a[1,..]
3-element MArray{Tuple{3},Float64,1,3} with indices SOneTo(3):
 0.3218188726238625
 1.307030516467493
 0.16583612823771224
```
and I get `MArray` instead of `SArray`. Note that `StaticArrays` also partially circumvents `to_indices`: https://github.com/JuliaArrays/StaticArrays.jl/blob/59f92e0ca7ac391a850a6e7a2ce1eb53aa237fc4/src/indexing.jl#L225 .

**Comment by ranocha** [comment]
You're right, StaticArrays.jl and EllipsisNotation do also not work together as they should, since
```julia
julia> using Pkg; Pkg.activate(temp=true); Pkg.add(["EllipsisNotation", "HybridArrays", "StaticArrays"]); using EllipsisNotation, HybridArrays, StaticArrays
[...]
  [da5c29d0] + EllipsisNotation v1.0.0
  [1baab800] + HybridArrays v0.4.4
  [90137ffa] + StaticArrays v1.0.1
[...]

julia> a = @SMatrix randn(3,3)
3×3 SArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
  1.2857    1.52985    1.49314
 -0.814121  1.67052   -0.0925791
 -0.230291  0.848189   0.934648

julia> a[1, :] # gives an SArray
3-element SArray{Tuple{3},Float64,1,3} with indices SOneTo(3):
 1.2857007082151861
 1.5298533524538094
 1.4931356369002144

julia> a[1, ..] # gives an MArray
3-element MArray{Tuple{3},Float64,1,3} with indices SOneTo(3):
 1.2857007082151861
 1.5298533524538094
 1.4931356369002144
```
However, it seems to work at least (in the sense of throwing no error). Continuing the example above,
```julia
julia> view(a, 1, :)
3-element view(::SArray{Tuple{3,3},Float64,2,9}, 1, :) with eltype Float64 with indices SOneTo(3):
 1.2857007082151861
 1.5298533524538094
 1.4931356369002144

julia> view(a, 1, ..)
3-element view(::SArray{Tuple{3,3},Float64,2,9}, 1, :) with eltype Float64 with indices SOneTo(3):
 1.2857007082151861
 1.5298533524538094
 1.4931356369002144

julia> b = HybridArray{Tuple{3, 3}}(rand(3, 3))
3×3 HybridArray{Tuple{3,3},Float64,2,2,Array{Float64,2}} with indices SOneTo(3)×SOneTo(3):
 0.038654  0.706119  0.151672
 0.530268  0.806502  0.835772
 0.280619  0.915615  0.179368

julia> view(b, 1, :)
3-element SizedArray{Tuple{3},Float64,1,1,SubArray{Float64,1,HybridArray{Tuple{3,3},Float64,2,2,Array{Float64,2}},Tuple{Int64,Base.Slice{SOneTo{3}}},true}} with indices SOneTo(3):
 0.03865400819804554
 0.7061190888149158
 0.1516722054538031

julia> view(b, 1, ..)
ERROR: MethodError: no method matching all_dynamic_fixed_val(::Type{Tuple{3,3}}, ::Int64, ::EllipsisNotation.Ellipsis)
Closest candidates are:
  all_dynamic_fixed_val(::Type{Size}, ::Union{Colon, Int64, AbstractArray}...) where Size<:Tuple at HybridArrays/GeLeK/src/HybridArrays.jl:52
  all_dynamic_fixed_val(::Type{Size}) where Size<:Tuple at HybridArrays/GeLeK/src/HybridArrays.jl:44
  all_dynamic_fixed_val(::Type{Size}, ::StaticArrays.StaticIndexing{var"#s14"} where var"#s14"<:Union{Colon, Int64, AbstractArray}...) where Size<:Tuple at HybridArrays/GeLeK/src/HybridArrays.jl:48
Stacktrace:
 [1] view(::HybridArray{Tuple{3,3},Float64,2,2,Array{Float64,2}}, ::Int64, ::EllipsisNotation.Ellipsis) at HybridArrays/GeLeK/src/indexing.jl:304
 [2] top-level scope at REPL[32]:1
```
I'm not an expert on every detail of indexing in Julia either, but I think it would be good to provide some working fallback methods such that something like the `view` above works. We would really like to use this to speed up some computations.

**Comment by ranocha** [comment]
Maybe another approach would be to use the same tactic as StaticArrays and just fall back to base methods for something not recognized by HybridArrays, i.e. to restrict new `getindex`, `view` etc. methods to known index types? For example, https://github.com/mateuszbaran/HybridArrays.jl/blob/1550dab049279d0e3a1d5e97a634b1905907c3ca/src/indexing.jl#L299-L305 could become
```julia
@inline function Base.view( 
     a::HybridArray{S}, 
     indices::Union{Colon, Int, AbstractArray}..., 
 ) where {S} 
     inner_view = invoke(view, Tuple{AbstractArray, typeof(indices).parameters...}, a, indices...) 
     return _view_hybrid(a, all_dynamic_fixed_val(S, indices...), inner_view, indices...) 
 end 
```

**Comment by ranocha** [comment]
I would also argue that the problem lies more on the side of EllipsisNotation, since
```julia
julia> a = @SArray rand(2,3,4);

julia> a[:, CartesianIndex(1, 2)]
2-element MArray{Tuple{2},Float64,1,2} with indices SOneTo(2):
 0.2986268295107888
 0.9195744224253837

julia> view(a, :, CartesianIndex(1, 2))
2-element view(::SArray{Tuple{2,3,4},Float64,3,24}, :, 1, 2) with eltype Float64 with indices SOneTo(2):
 0.2986268295107888
 0.9195744224253837
julia> b = HybridArray{Tuple{2, 3, 4}}(rand(2, 3, 4));

julia> b[:, CartesianIndex(1, 2)]
2-element HybridArray{Tuple{2},Float64,1,1,Array{Float64,1}} with indices SOneTo(2):
 0.5847068898984851
 0.8900340411185412

julia> view(b, :, CartesianIndex(1, 2))
ERROR: MethodError: no method matching all_dynamic_fixed_val(::Type{Tuple{2,3,4}}, ::Colon, ::CartesianIndex{2})
Closest candidates are:
  all_dynamic_fixed_val(::Type{Size}, ::Union{Colon, Int64, AbstractArray}...) where Size<:Tuple at HybridArrays/GeLeK/src/HybridArrays.jl:52
  all_dynamic_fixed_val(::Type{Size}) where Size<:Tuple at HybridArrays/GeLeK/src/HybridArrays.jl:44
  all_dynamic_fixed_val(::Type{Size}, ::StaticArrays.StaticIndexing{var"#s14"} where var"#s14"<:Union{Colon, Int64, AbstractArray}...) where Size<:Tuple at HybridArrays/GeLeK/src/HybridArrays.jl:48
Stacktrace:
 [1] view(::HybridArray{Tuple{2,3,4},Float64,3,3,Array{Float64,3}}, ::Function, ::CartesianIndex{2}) at HybridArrays/GeLeK/src/indexing.jl:304
 [2] top-level scope at REPL[12]:1
```

**Comment by ranocha** [comment]
I implemented the idea described in https://github.com/mateuszbaran/HybridArrays.jl/pull/41#issuecomment-774978010 and added new tests for Cartesian indices. Now, `view`s should work at least with various index types but they will fall back to generic methods from `Base`, similar to StaticArrays.

This solves the immediate error from `view` but does not really solve the general background issue with non-standard indices relying on `to_indices`. Maybe it would be worth starting a discussion on Discourse (and merge this PR as a hotfix for now)?

**Comment by mateuszbaran** [comment]
I think this is a good hotfix for this problem. Next, we probably need to overload `Base._getindex` since it's called after `to_indices`, with some methods that would return something better than the default.

We can discuss it either here or on Discourse, your choice :slightly_smiling_face: .

Could you bump the patch version so I can merge & tag this?

**Comment by ranocha** [comment]
> Could you bump the patch version so I can merge & tag this?

Sure :+1:

**Comment by ranocha** [comment]
> Next, we probably need to overload `Base._getindex` since it's called after `to_indices`, with some methods that would return something better than the default.
> 
> We can discuss it either here or on Discourse, your choice.

Both is fine for me, but I guess creating a thread on Discourse might attract more people from outside who are also involved in indexing, say in Base and StaticArrays.

**Pull request merged**
